### PR TITLE
Update postgres version in travis build

### PR DESCRIPTION
**Pull request by elizabethengelman**

### CODE REVIEW

**Comment by daimesava** [comment]
Postgres 12 is not yet available in RDS. 11.6 is the latest available there.

**Comment by elizabethengelman** [comment]
Thanks for that info @daimesava. Just pushed up a change to our schema and travis to use pg 11.6 - is that cool with you that we upgrade from 11.2 to 11.6 in our deployment?

**Comment by daimesava** [comment]
Of course. Current deployment is on 11.5, but upgrade is trivial. Just ping me when you want it done. New deployments will be with 11.6

**Comment by elizabethengelman** [comment]
Okay cool! I think we'll plan to cut `staging` over to `master` today/tomorrow, and will be ready for a new deployment. And then I'm cool with upgrading the current deployment whenever, or even not worrying about it until the new deployment.

**Pull request merged**
